name: CI-Tests

on:
  pull_request:
    branches:
      - dev*
    
  push:
    branches:
      - main
    

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Pipenv environment
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python  
        uses: actions/setup-python@v2
        # with:
          # python-version: 3.12.3

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Run unit tests
        run: pipenv run pytest test/

      - name: Lint
        run: pipenv run pylint --recursive=y .

      